Add php-apache template

diff --git a/templates/php-apache/docker-compose.yml b/templates/php-apache/docker-compose.yml
--- a/templates/php-apache/docker-compose.yml
+++ b/templates/php-apache/docker-compose.yml
@@ -13,8 +13,11 @@ services:
       - ${PHP_WEB_ROOT:-./app}:/var/www/html
     command: >
       /bin/bash -c "
-      if [ -n $${PHP_EXTENSIONS+x} ]; then
-        docker-php-ext-install $$PHP_EXTENSIONS || exit 1;
+      if [ -n \"${PHP_EXTENSIONS+x}\" ]; then
+        docker-php-ext-install $$PHP_EXTENSIONS || { 
+          echo 'Error installing PHP extensions via docker-php-ext-install - check your docker-compose.yml command: section'; 
+          exit 1; 
+        }
       fi &&
       if ! grep -q 'ServerName' /etc/apache2/apache2.conf; then
         echo 'ServerName $$APACHE_SERVER_NAME' >> /etc/apache2/apache2.conf;
